openai_api_key: ""

plan_switch:
  model: "gpt-4o-2024-08-06"
  temperature: 0.0
  memory_length: 3

plan_write:
  model: "gpt-4o-2024-08-06"
  temperature: 0.0

plan_answer:
  model: "gpt-4o-mini"
  temperature: 0.2

plan_memory:
  max_tokens: 110000
  compressed_tokens: 8000
  temperature: 0.3
  model: "gpt-4o-mini"

code_write:
  model: "gpt-4o-2024-08-06"
  temperature: 0.0

code_insight:
  model: "gpt-4o"
  temperature: 0.5

code_ranking:
  model: "gpt-4o-2024-08-06"
  temperature: 0.1
  memory_length: 5

code_answer:
  model: "gpt-4o-mini"
  temperature: 0.2
  memory_length: 5

code_switch:
  model: "gpt-4o-2024-08-06"
  temperature: 0.0
  memory_length: 3

code_memory:
  max_tokens: 110000
  compressed_tokens: 8000
  temperature: 0.2
  model: "gpt-4o-mini"

image_gen:
  model: "gpt-4o-2024-08-06"
  image_gen_model: "dall-e-3"
  size: "1024x1024" # 1792x1024
  quality: "standard"
  temperature: 0.4

image_ranking:
  model: "gpt-4o-2024-08-06"
  temperature: 0.1

image_gen_memory:
  max_tokens: 110000
  compressed_tokens: 8000
  temperature: 0.2
  model: "gpt-4o-mini"

game_list:
  - "俄罗斯方块"
  - "五子棋"
  - "跳一跳"
  - "2048"
  - "扫雷"
  - "推箱子"
  - "马里奥闯关"
  - "打地鼠"
  - "打砖块"
  - "打气球"
  - "打字游戏"
  - "贪吃蛇"