openai_api_key: "" # .streamlit/secrets.toml

plan_switch:
  model: "gpt-4o-2024-08-06"
  temperature: 0.0
  k: 3

plan_writing:
  model: "gpt-4o-2024-08-06"
  temperature: 0.0

plan_answer:
  model: "gpt-4o-mini"
  temperature: 0.2

plan_memory:
  max_tokens: 110000
  compressed_tokens: 8000
  temperature: 0.3
  model: "gpt-4o-mini"

code_memory:
  max_tokens: 110000
  compressed_tokens: 8000
  temperature: 0.2
  model: "gpt-4o-mini"

code_writing:
  model: "gpt-4o-2024-08-06"
  temperature: 0.0

code_insight:
  model: "gpt-4o"
  temperature: 0.5

code_ranking:
  model: "gpt-4o-2024-08-06"
  temperature: 0.1
  k: 1

code_answer:
  model: "gpt-4o-mini"
  temperature: 0.2
  k: 3

code_switch:
  model: "gpt-4o-2024-08-06"
  temperature: 0.0
  k: 1

img_memory:
  max_tokens: 110000
  compressed_tokens: 8000
  temperature: 0.2
  model: "gpt-4o-mini"

img_gen:
  model: "dall-e-3"
  temperature: -1.0 # deprecated